# Generated by Django 4.0.6 on 2022-07-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scheduled_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=120, verbose_name='Student Name')),
                ('student_email', models.EmailField(max_length=254, verbose_name='Student Email')),
                ('weekday', models.CharField(max_length=120, verbose_name='Weekday')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('date', models.DateField(verbose_name='Date')),
            ],
        ),
    ]
